name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Pake
      run: npx pake setup

    - name: Build application
      run: npx pake build

    - name: Upload artifact
      uses: actions/upload-artifact@v2with:
        name: BaiduDesktopApp
        path: ./output/*